### ISSUE TITLE
Improve UI of keyboard shortcuts

### ISSUE THREAD

**Issue by neocotic** [template-extension/template-chrome#201]
This can be done easily. First, **replace** the following lines (currently separate) from `popup.css`:

``` css
#templates li > a .pull-right {color: #999;}
#templates li > a:hover .pull-right {color: #FFF;}
```

With:

``` css
#templates li > a .shortcut {font-family: Consolas, "Liberation Mono", Courier, monospace; font-size: 12px;}
#templates li > a:hover .shortcut {color: #FFF;}
```

And change the following in the `buildTemplate` function within `background.coffee`:

``` coffeescript
  if template.shortcut and store.get 'shortcuts.enabled'
    anchor.append $ '<span/>',
      class: 'pull-right muted shortcut'
      html:  "#{ext.modifiers()}#{template.shortcut}"
```

This same sort of change should also be applied to the _Shortcut_ column on the Templates tab of the options page.
